name: C++ Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up C++ Environment
        uses: actions/setup-cpp@v2
        with:
          compiler: "gcc-11" # Specify the desired C++ compiler version

      - name: Configure and Build
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Run Tests
        run: |
          cd build
          ctest --verbose
